language: python
python:
  - "3.4"

env:
  - CODECLIMATE_REPO_TOKEN=fa9e0617b8778a1186d75363c3c6ddc119d2cb360abdabcd2c85a0cbc35ee87e

addons:
  apt:
    packages:
      - graphviz
  code_climate:
    repo_token: fa9e0617b8778a1186d75363c3c6ddc119d2cb360abdabcd2c85a0cbc35ee87e

# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt
  - pip install -r requirements_travis.txt

# command to run tests
script:
  pytest -s --verbose --cov=algo algo/tests/ && codecov && coveralls && codeclimate-test-reporter

# run performance test without profiling
after_success:
  pytest -s --verbose algo/tests/perf/
