language: python
python:
  - "3.4"

env:
  - CODECLIMATE_REPO_TOKEN=fa9e0617b8778a1186d75363c3c6ddc119d2cb360abdabcd2c85a0cbc35ee87e

addons:
  code_climate:
    repo_token: fa9e0617b8778a1186d75363c3c6ddc119d2cb360abdabcd2c85a0cbc35ee87e

# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty

# command to install dependencies
install:
  - pip install pytest-sugar
  - pip install pytest-cov
  - pip install coveralls
  - pip install codeclimate-test-reporter

# command to run tests
script: pytest -s --verbose algo/tests/

after_success:
  pytest -s --verbose --cov=algo algo/tests/ && coveralls && codeclimate-test-reporter
